# Example configuration file for molecular dynamics simulation
# Usage: python _md.py --config md_config_example.yaml

# SMILES string of the molecule to simulate
smiles: "CNCc1cccc(c1)C"

# Directory where all output files will be saved (trajectories, PDB files, CSV data)
save_dir: "/home/ubuntu/scratch/monorepo/pyclops/pyclops/losses/kdes/_records/_simulations/lys-phe"

# Number of seeds for multiple simulations (will create range(seeds))
seeds: 10

# Interval for saving trajectory frames
checkpoint_interval: 100

# Interval for printing simulation progress to stdout
printout_interval: 10000

# Total number of MD steps to run
steps: 5000000 